version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    container_name: mysql
